[theme]
base="dark"
primaryColor="#61AFEF"             # 파란색 포인트 (버튼 등)
backgroundColor="#282C34"          # 메인 배경색
secondaryBackgroundColor="#21252B" # 입력 박스/카드 배경
textColor="#ABB2BF"                # 기본 텍스트 색상

[client]
showSidebarNavigation = false